Add Php Feature
IntelLabs/control-flag pull request #40
Opened 2022-02-05 11:41 UTC by kotauchisunsun

I want to analyze php code by control-flag. so, I make it.

2022-03-09 20:00 UTC, nhasabni commented
Hi @kotauchisunsun,

Great to see your PR that adds support for PHP! I will review it in the next couple of days. Thanks for your efforts again.

2022-03-09 20:04 UTC, nhasabni commented on scripts/mine_patterns.sh
> +  find "${TRAIN_DIR}" -iname "*.php" -type f | fgrep -v "/vendor/" > ${FILE_LIST}
It looks like `/vendor` is environment specific? Not sure what is fgrep for? Can you please clarify?

2022-03-09 20:05 UTC, nhasabni commented on scripts/mine_patterns.sh
>    echo "ERROR: Only 1 (C) and 2 (Verilog) are supported languages; received ${LANGUAGE}"
I think the error message needs to be updated to include PHP now.

2022-03-09 20:06 UTC, nhasabni commented on scripts/scan_for_anomalies.sh
> +  find "${SCAN_DIR}" -iname "*.php" -type f | fgrep -v "/vendor/" > ${SCAN_FILE_LIST}
It looks like /vendor is environment specific? Not sure what is fgrep for? Can you please clarify?

2022-03-09 23:07 UTC, nhasabni commented on src/common_util.cpp
> +// For PHP language, we are looking for control structures such as if statements.
This line is more than 80 chars long. Can you please convert it into two lines?

2022-03-09 23:07 UTC, nhasabni commented on src/common_util.cpp
> +// For PHP language, we are looking for control structures such as if statements.
This line is more than 80 chars long. Can you please convert it into two lines?

2022-03-09 23:17 UTC, nhasabni commented on src/common_util.cpp
> +
It looks like for both C and PHP, we are collecting `if` statements only. If that is correct, can you please convert the function for C language into a generic one? LANGUAGE_C and LANGUAGE_PHP specific instantiations will then take care of building language specific implementation. What I mean is to convert:
```
template <>
void CollectCodeBlocksOfInterest<LANGUAGE_C>(const TSNode& node,
    code_blocks_t& code_blocks) {
  if (ts_node_is_null(node)) { return; }
  uint32_t count = ts_node_child_count(node);
  for (uint32_t i = 0; i < count; i++) {
    auto child = ts_node_child(node, i);
    if (ts_node_is_null(child)) continue;
    if (IsIfStatement<LANGUAGE_C>(child)) {
      auto if_condition = GetIfConditionNode<LANGUAGE_C>(child);
      if (!ts_node_has_error(if_condition)) {
        code_blocks.push_back(if_condition);
      }
    }
    CollectCodeBlocksOfInterest<LANGUAGE_C>(child, code_blocks);
  }
}
```

into a generic function like:

```
template <Language L>
void CollectCodeBlocksOfInterest(const TSNode& node,
    code_blocks_t& code_blocks) {
  if (ts_node_is_null(node)) { return; }

  uint32_t count = ts_node_child_count(node);
  for (uint32_t i = 0; i < count; i++) {
    auto child = ts_node_child(node, i);
    if (ts_node_is_null(child)) continue;
    if (IsIfStatement<L>(child)) {
      auto if_condition = GetIfConditionNode<L>(child);
      if (!ts_node_has_error(if_condition)) {
        code_blocks.push_back(if_condition);
      }
    }
    CollectCodeBlocksOfInterest<L>(child, code_blocks);
  }
}
```

We can then remove PHP specific instantiation.

2022-03-09 23:17 UTC, nhasabni commented on src/common_util.cpp
> +
It looks like for both C and PHP, we are collecting `if` statements only. If that is correct, can you please convert the function for C language into a generic one? LANGUAGE_C and LANGUAGE_PHP specific instantiations will then take care of building language specific implementation. What I mean is to convert:
```
template <>
void CollectCodeBlocksOfInterest<LANGUAGE_C>(const TSNode& node,
    code_blocks_t& code_blocks) {
  if (ts_node_is_null(node)) { return; }
  uint32_t count = ts_node_child_count(node);
  for (uint32_t i = 0; i < count; i++) {
    auto child = ts_node_child(node, i);
    if (ts_node_is_null(child)) continue;
    if (IsIfStatement<LANGUAGE_C>(child)) {
      auto if_condition = GetIfConditionNode<LANGUAGE_C>(child);
      if (!ts_node_has_error(if_condition)) {
        code_blocks.push_back(if_condition);
      }
    }
    CollectCodeBlocksOfInterest<LANGUAGE_C>(child, code_blocks);
  }
}
```

into a generic function like:

```
template <Language L>
void CollectCodeBlocksOfInterest(const TSNode& node,
    code_blocks_t& code_blocks) {
  if (ts_node_is_null(node)) { return; }

  uint32_t count = ts_node_child_count(node);
  for (uint32_t i = 0; i < count; i++) {
    auto child = ts_node_child(node, i);
    if (ts_node_is_null(child)) continue;
    if (IsIfStatement<L>(child)) {
      auto if_condition = GetIfConditionNode<L>(child);
      if (!ts_node_has_error(if_condition)) {
        code_blocks.push_back(if_condition);
      }
    }
    CollectCodeBlocksOfInterest<L>(child, code_blocks);
  }
}
```

We can then remove PHP specific instantiation.

2022-03-09 23:19 UTC, nhasabni commented on src/parser.h
>    LANGUAGE_C = 1,
Minor nit: Can you please put "{" on the same line as `enum Language`?

2022-03-09 23:19 UTC, nhasabni commented on src/parser.h
>    LANGUAGE_C = 1,
Minor nit: Can you please put "{" on the same line as `enum Language`?

2022-03-09 23:21 UTC, nhasabni commented on src/tree-sitter/CMakeLists.txt
> +)
Can you please add a newline at the end of this file?

2022-03-09 23:21 UTC, nhasabni commented on src/tree-sitter/CMakeLists.txt
> +)
Can you please add a newline at the end of this file?

2022-03-09 23:28 UTC, nhasabni requested changes
Thanks again for your wonderful contribution, @kotauchisunsun! It looks great overall. Had some minor comments. Please take a look.

2022-03-11 17:29 UTC, kotauchisunsun commented
Thank you for your code review.

> find "${TRAIN_DIR}" -iname "*.php" -type f | fgrep -v "/vendor/" > ${FILE_LIST}
> It looks like /vendor is environment specific? Not sure what is fgrep for? Can you please clarify?

Phper use package manager, composer.
Composer resolves library dependencies  and installs the libraries.
It is installed in the `vendor/` directory.
`fgrep -v "/vendor/"` will remove third-party libraries in the project (not a complete solution).

https://getcomposer.org/doc/01-basic-usage.md

2022-03-11 18:27 UTC, nhasabni commented on src/common_util.cpp
> +// For PHP language, we are looking for control structures such as if statements.
It looks like the stylechecker is reporting an error for this line - it is more than 80 chars long.

2022-03-11 18:31 UTC, nhasabni approved these changes
Hi @kotauchisunsun,

Thanks again for your efforts! This is amazing work. As a last request, can you please fix the style errors reported for the PR? You can check the error report here - https://github.com/IntelLabs/control-flag/actions/runs/1970075074

2022-03-12 06:18 UTC, kotauchisunsun commented
@nhasabni 

Thank you. I fix it.

2022-03-14 05:15 UTC, nhasabni commented
Thanks @kotauchisunsun for your wonderful contribution! Really appreciate it.

2022-03-14 05:15 UTC, merged